# Generated by Django 3.1.7 on 2021-03-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=60)),
                ('LastName', models.CharField(blank=True, default='', max_length=60)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=40)),
            ],
        ),
    ]
