# Generated by Django 3.1.7 on 2021-03-28 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210327_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='PREFIX_CHOICES',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
