# Generated by Django 3.1.7 on 2021-03-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210328_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='type',
        ),
        migrations.AddField(
            model_name='profiles',
            name='Prefix',
            field=models.CharField(blank=True, choices=[('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('', '')], default='', max_length=6),
        ),
    ]
