# Generated by Django 3.1.7 on 2021-03-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210328_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Prefix',
            field=models.CharField(blank=True, choices=[('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('', ''), ('Mr.', 'Mr.')], default='', max_length=6),
        ),
    ]
