# Generated by Django 3.1.7 on 2021-04-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20210331_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Prefix',
            field=models.CharField(blank=True, choices=[('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('', '')], default='', max_length=6),
        ),
    ]
