# Generated by Django 3.1.7 on 2021-04-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20210331_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Prefix',
            field=models.CharField(blank=True, choices=[('', ''), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='Username',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
